
## Time Series

Extracts characteristics from time-sequenced data, which may exhibit the following characteristics:
- Stationarity - statistical properties such as mean, variance, and auto correlation are constant over time
- Trend - long-term rise or fall in values
- Seasonality - variations associated with specific calendar times, occurring at regular intervals less than a year
- Cyclicality - variations without a fixed time length, occurring in periods of greater or less than one year
- Autocorrelation - degree of linear similarity between current and lagged values

CV must account for the time aspect, such as for each fold $F_x$:

- Sliding Window - train $F_1$, test $F_2$, then train $F_2$, test $F_3$
- Forward Chain - train $F_1$, test $F_2$, then train $F_1, F_2$, test $F_3$

#### Exponential Smoothing 
uses an exponentially decreasing weight to observations over time, and takes a moving average. The time $t$ output is $s_t = \alpha x_t + (1-\alpha)s_{t-1}$, where  $0 < \alpha < 1$.

#### Double Exponential Smoothing  
applies a recursive exponential filter to capture trends within a time series

$$s_t = \alpha x_t + (1-\alpha)(s_{t-1} + b_{t-1})$$

$$b_t = \beta (s_t - s_{t-1}) + (1-\beta)b_{t-1}$$

Triple exponential smoothing adds a third variable
$\gamma$ that accounts for seasonality.
\smallskip

#### ARIMA 
models time series using three parameters $(p,d,q)$:

- Autoregressive - the past $p$ values affect the next value

- Integrated - values are replaced with the difference between current and previous values, using the difference degree $d$ (0 for stationary data, and 1 for non-stationary)

- Moving Average - the number of lagged forecast errors and the size of the moving average window $q$

#### SARIMA  
models seasonality through four additional seasonality-specific parameters: $P$, $D$, $Q$, and the season length $s$

#### Prophet  
additive model that uses non-linear trends to account for multiple seasonalities such as yearly, weekly, and daily. Robust to missing data and handles outliers well.\\ Can be represented as: $y(t) = g(t) + s(t) + h(t) + \epsilon(t)$, with four distinct components for the growth over time, seasonality, holiday effects, and error. This specification is similar to a generalized additive model.

#### Generalized Additive Model  
combine predictive methods while preserving additivity across variables, in a form such as
$y = \beta_0 + f_1(x_1) + \cdots + f_m(x_m)$, where functions can be non-linear. GAMs also provide regularized and interpretable solutions for regression and classification problems.

Classifies data using the label with the highest conditional probability, given data $a$ and classes $c$. Naive because it assumes variables are independent.