---
title: Data-Science Cheat Sheet
author: Miguel R.
---
# Data Science Cheat sheet
## Statistics
### Discrete Distributions
#### Binomial
number of successes $x$ in $n$ events,
each with $p$ probability $\to \binom{n}x p^x q^{n-x}$, 
with $\mu = np$ and $\delta^2 = npq$. If n = 1, this is Bernoulli.


#### Geometric  
first success with $p$ probability on the $n^{th}$ trial $\to q^{n-1}p$, with mean = $1/p$

#### Negative Binomial 
number of failures before $r$ successes 

#### Hypergeometric 
number of successes $x$ in a size $N$ population with $n$ draws, without replacement. 
$$\mu=n\frac{x}{N}$$

#### Poisson 
number of successes $x$ in a fixed time interval, 
where success occurs at an average rate $\lambda$ $\to$ $\frac{\lambda^xe^{-\lambda}}{x!}$. 
$\mu = \delta^2 = \lambda$


### Continuous Distributions

#### Uniform 
all values between $a$ and $b$ are equally likely $\to \frac{1}{b-a}$ with $\mu = \frac{a+b}{2}$ and $\sigma^2 = \frac{(b-a)^2}{12}$ or $\frac{n^2 - 1}{12}$ if discrete

#### Normal/Gaussian 
$N(\mu,\sigma$), Standard Normal $Z\sim N(0, 1)$

- Central Limit Theorem - sample mean of i.i.d. data approaches normal distribution
- Empirical Rule - 68\%, 95\%, and 99.7\% of values lie within one, two, and three standard deviations of the mean
- Normal Approximation - discrete distributions such as Binomial and Poisson can be approximated using z-scores when $np$, $nq$, and $\lambda$ are greater than 10
\end{itemize}

#### Exponential 
memoryless time between independent events occurring at an average rate $\lambda$ $\to \lambda e^{-\lambda x}$, with $\mu$ = $\frac{1}{\lambda}$

#### Gamma 
time until $n$ independent events occurring at an average rate $\lambda$

## Concepts

Prediction Error = Bias$^2$ + Variance + Irreducible Noise

### Bias 
wrong assumptions when training $\to$ can't capture underlying patterns $\to$ underfit

### Variance 
sensitive to fluctuations when training$\to$ can't generalize on unseen data $\to$ overfit

The bias-variance tradeoff attempts to minimize these two sources of error, through methods such as:

- Cross validation to generalize to unseen data
- Dimension reduction and feature selection

In all cases, as variance decreases, bias increases.
ML models can be divided into two types:
    - Parametric - uses a fixed number of parameters with respect to sample size
    - Non-Parametric - uses a flexible number of parameters and doesn't make particular assumptions on the data

### Cross Validation 
validates test error with a subset of training data, and selects parameters to maximize average performance
- $k$-fold - divide data into $k$ groups, and use one to validate
- leave-$p$-out  - use $p$ samples to validate and the rest to train

## Model Evaluation
### Regression

#### Mean Squared Error (MSE) 
$\frac{1}{n}\sum (y_i -\hat{y})^2$

Sum of Squared Error (SSE) = $\sum (y_i - \hat{y})^2$

Total Sum of Squares (SST) = $\sum (y_i - \bar{y})^2$
\vspace{.1em}

#### $\boldsymbol{R^2}$
$1 - \frac{SSE}{SST}$, the proportion of explained $y$-variability

Note, negative $R^2$ means the model is worse than just predicting the mean. $R^2$ is not valid for nonlinear models, as $SS_{residual } + SS_{error} \neq SST$.


#### Adjusted $\boldsymbol{R^2}$ 
$1 - (1-R^2)\frac{N-1}{N-p-1}$, which changes only when predictors affect $R^2$ above what would be expected by chance

### Classification
||Predict Yes|Predict No|
|---|---|---|
|**Actual Yes**| **T**rue **P**ositive ($1-\beta$)|**F**alse **N**egative ($\beta$)|
|**Actual No** | **F**alse **P**ositive ($\alpha$)| **T**rue **N**egative ($1-\alpha$)|


- Precision = $\frac{TP}{TP + FP}$, percent correct when predict positive
- Recall, Sensitivity = $\frac{TP}{TP + FN}$, percent of actual positives identified correctly (True Positive Rate)
- Specificity = $\frac{TN}{TN + FP}$, percent of actual negatives identified correctly, also 1 - FPR (True Negative Rate)
- $F_1 = 2\frac{precision\cdot recall}{precision + recall}$, useful when classes are **imbalanced**

#### ROC Curve
plots TPR (True Positive Rate) vs. FPR (False Positive Rate) for every threshold $\alpha$. 
Area Under the Curve  *measures how likely the model differentiates positives and negatives* (perfect AUC = 1, baseline = 0.5).


#### Precision-Recall Curve
focuses on the *correct prediction of the minority class*, useful when data is imbalanced

## Linear Regression
Models linear relationships between a continuous response and explanatory variables


### Ordinary Least Squares  
find $\hat{\beta}$ for $\hat{y} = \hat{\beta_{0}} + \hat{\beta}X + \epsilon$
by solving $\hat{\beta}$ = $(X^{T}X)^{-1}X^{T}Y$ which minimizes the SSE

### Assumptions
- Linear relationship and independent observations
- Homoscedasticity - error terms have constant variance
- Errors are uncorrelated and normally distributed
- Low multicollinearity


### Variance Inflation Factor 
measures the severity of multicollinearity $\to$ $\frac{1}{1-{R_i}^2}$, where ${R_i}^2$ is found by regressing $X_i$ against all other variables (a common VIF cutoff is 10)

### Regularization

Add a penalty $\lambda$ for large coefficients to the cost function, which reduces overfitting. Requires normalized data.

### Subset  $(L_0)$
$\lambda ||\hat{\beta}||_0 = \lambda (number \;of\;non\hspace{-.7mm}-\hspace{-.7mm}zero\; variables)$

### LASSO  ($L_1$)
$\lambda ||\hat{\beta}||_1 = \lambda\sum | \hat{\beta} |$

### Ridge  $(L_2)$
$\lambda ||\hat{\beta}||_2 = \lambda\sum( \hat{\beta})^2$

::: {.callout-note}
Combining LASSO and Ridge gives Elastic Net
:::

## LogisTic Regression

Predicts probability that $y$ belongs to a binary class. Estimates $\beta$ through maximum likelihood estimation (MLE) by fitting a logistic (sigmoid) function to the data. This is equivalent to minimizing the cross entropy loss. Regularization can be added in the exponent.





